---
# tasks file for php
- name: Install php extensions & composer
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - libapache2-mod-php7.4
    - php7.4-gd
    - php-ssh2
    - php7.4
    - php7.4-cli
    - php7.4-mysql

- name: Install Composer
  shell: >
    curl -sS https://getcomposer.org/installer | php
    && mv composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer
  become: yes
